# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 16:25
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('akiba', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.CharField(default=datetime.datetime(2016, 9, 18, 16, 25, 1, 903319), max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image_thumbnail',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='akiba.Post'),
        ),
        migrations.AddField(
            model_name='post',
            name='sponsored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='sticky',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='texthtml',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='thread_type',
            field=models.CharField(choices=[(b'QQ', b'Question'), (b'DD', b'Discussion'), (b'LL', b'Link')], default=b'DD', max_length=2, null=True),
        ),
    ]
