# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akiba', '0002_auto_20160918_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_thumbnail',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(upload_to=b'uploads/images/%Y/%m/%d/%H/%M/%S/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='texthtml',
            field=models.TextField(null=True),
        ),
    ]
