version: '3'

services:
  web:
    image: askapp
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      WAIT_HOSTS: mysql:3306
      DB_HOST: mysql
      DB_NAME: askapp
      DJANGO_SECRET: askapp
      DB_USER: root
      DB_PASSWORD: askapp
      EMAIL_ADDRESS: askapp@askapp.com
      EMAIL_HOST: askapp
      EMAIL_HOST_PASSWORD: askapp
    #volumes:
    #  - .:/code
    command: sh -c "cp -r docker/media askapp && /wait && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7.19
    volumes:
      - ./docker/sql:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: askapp
      MYSQL_ROOT_PASSWORD: askapp
    restart: always

volumes:
  dbdata:
