# Generated by Django 2.2.5 on 2019-11-09 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('askapp', '0017_auto_20191105_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='original',
            field=models.ForeignKey(blank=True, null=True, db_index=True, on_delete=django.db.models.deletion.SET_NULL, to='askapp.Thread'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='thread_type',
            field=models.CharField(choices=[('DD', 'Discussion'), ('LL', 'Link'), ('YT', 'Youtube video'), ('DU', 'Duplicate thread')], default='LL', max_length=2, null=True),
        ),
    ]
