# Generated by Django 2.2.5 on 2019-11-19 08:46

from django.db import migrations, models
import django.db.models.deletion


def add_level(apps, schema_editor):
    UserLevel = apps.get_model("askapp", "UserLevel")
    db_alias = schema_editor.connection.alias
    UserLevel.objects.using(db_alias).bulk_create([
        UserLevel(name="Level 1"),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('askapp', '0018_auto_20191109_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('upvotes', models.IntegerField(default=3)),
                ('downvotes', models.IntegerField(default=0)),
                ('upvote_same', models.IntegerField(default=1)),
                ('downvote_same', models.IntegerField(default=1)),
            ],
        ),
        migrations.RunPython(add_level),
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='askapp.UserLevel'),
        ),
    ]
