# Generated by Django 3.1 on 2020-11-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askapp', '0019_auto_20191119_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Activity log',
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='thread',
            name='thread_type',
            field=models.CharField(choices=[('DD', 'Discussion'), ('LL', 'Link'), ('YT', 'Youtube video'), ('DU', 'Duplicate thread'), ('VS', 'Video stream')], default='LL', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='userlevel',
            name='downvote_same',
            field=models.IntegerField(default=1, verbose_name='Downvote same article'),
        ),
        migrations.AlterField(
            model_name='userlevel',
            name='upvote_same',
            field=models.IntegerField(default=1, verbose_name='Upvotes of the same article'),
        ),
        migrations.AlterField(
            model_name='userlevel',
            name='upvotes',
            field=models.IntegerField(default=3, verbose_name='Upvotes per day'),
        ),
        migrations.DeleteModel(
            name='Action',
        ),
    ]
